# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1245868680);
user_pref("app.update.lastUpdateTime.background-update-timer", 1245868679);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1245868680);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1245868680);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1245868680);
user_pref("browser.anchor_color", "#0000FF");
user_pref("browser.display.background_color", "#C0C0C0");
user_pref("browser.display.use_system_colors", true);
user_pref("browser.download.manager.alertOnEXEOpen", true);
user_pref("browser.history_expire_days", 1);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1");
user_pref("browser.visited_color", "#800080");
user_pref("capability.policy.trusted.sites", "http://127.0.0.1");
user_pref("capability.principal.codebase.p0.granted", "UniversalPreferencesWrite UniversalXPConnect UniversalBrowserWrite UniversalPreferencesRead UniversalBrowserRead");
user_pref("capability.principal.codebase.p0.id", "http://127.0.0.1");
user_pref("extensions.enabledItems", "exeex@exelearning.org:0.4.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5,{9f08cb5a-76b1-4bcf-aff9-90e1a5d60b1e}:3.64");
user_pref("extensions.lastAppVersion", "3.5");
user_pref("extensions.update.notifyUser", false);
user_pref("general.open_location.last_url", "google.com");
user_pref("general.open_location.last_window_choice", 0);
user_pref("general.skins.selectedSkin", "Noia2f");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("spellchecker.dictionary", "en-US");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1248448934);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
