# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1239200879);
user_pref("app.update.lastUpdateTime.background-update-timer", 1241614709);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1241614709);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1241614709);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1251462572);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1241614709);
user_pref("avg.toolbar.first_installation", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "localhost:51235");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.4pre");
user_pref("browser.tabs.autoHide", true);
user_pref("browser.tabs.closeButtons", 2);
user_pref("capability.policy.allowclipboard.Clipboard.cutcopy", "allAccess");
user_pref("capability.policy.allowclipboard.Clipboard.paste", "allAccess");
user_pref("capability.policy.allowclipboard.sites", "http://127.0.0.1:8081 http://127.0.0.1:51235 http://127.0.0.1:51236");
user_pref("capability.policy.policynames", "allowclipboard");
user_pref("capability.principal.codebase.p0.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p0.id", "http://127.0.0.1:8081");
user_pref("capability.principal.codebase.p0.subjectName", "");
user_pref("capability.principal.codebase.p1.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p1.id", "http://127.0.0.1:51235");
user_pref("capability.principal.codebase.p1.subjectName", "");
user_pref("capability.principal.codebase.p10.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p10.id", "http://127.0.0.1:51243");
user_pref("capability.principal.codebase.p10.subjectName", "");
user_pref("capability.principal.codebase.p11.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p11.id", "http://127.0.0.1:51244");
user_pref("capability.principal.codebase.p11.subjectName", "");
user_pref("capability.principal.codebase.p12.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p12.id", "http://127.0.0.1:51245");
user_pref("capability.principal.codebase.p12.subjectName", "");
user_pref("capability.principal.codebase.p2.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p2.id", "http://127.0.0.1:51236");
user_pref("capability.principal.codebase.p2.subjectName", "");
user_pref("capability.principal.codebase.p3.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p3.id", "http://localhost:51235");
user_pref("capability.principal.codebase.p3.subjectName", "");
user_pref("capability.principal.codebase.p4.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p4.id", "http://127.0.0.1:51237");
user_pref("capability.principal.codebase.p4.subjectName", "");
user_pref("capability.principal.codebase.p5.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p5.id", "http://127.0.0.1:51238");
user_pref("capability.principal.codebase.p5.subjectName", "");
user_pref("capability.principal.codebase.p6.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p6.id", "http://127.0.0.1:51239");
user_pref("capability.principal.codebase.p6.subjectName", "");
user_pref("capability.principal.codebase.p7.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p7.id", "http://127.0.0.1:51240");
user_pref("capability.principal.codebase.p7.subjectName", "");
user_pref("capability.principal.codebase.p8.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p8.id", "http://127.0.0.1:51241");
user_pref("capability.principal.codebase.p8.subjectName", "");
user_pref("capability.principal.codebase.p9.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p9.id", "http://127.0.0.1:51242");
user_pref("capability.principal.codebase.p9.subjectName", "");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.disable_open_during_load", false);
user_pref("dom.disable_window_open_feature.status", false);
user_pref("dom.popup_allowed_events", "change click dblclick mouseup reset submit keypress contextmenu");
user_pref("extensions.checkCompatibility", false);
user_pref("extensions.enabledItems", "inspector@mozilla.org:2.0.0,exeex@exelearning.org:0.4.0,langpack-en-GB@firefox-3.0.ubuntu.com:3.0.7,refractor@developer.mozilla.org:0.9.9,langpack-en-GB@xulrunner-1.9.ubuntu.com:1.9.0.8,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5,{8181B740-5255-11D9-9FF6-0090995D2DCA}:0.8.09.07.17");
user_pref("extensions.ignoreMTimeChanges", true);
user_pref("extensions.update.autoUpdateEnabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.interval", 63072000);
user_pref("extensions.update.lastUpdateDate", 1339539111);
user_pref("extensions.update.notifyUser", false);
user_pref("general.open_location.last_url", "https://addons.mozilla.org/en-US/firefox/addon/1013");
user_pref("general.open_location.last_window_choice", 0);
user_pref("extensions.lastAppVersion", "3.5");
user_pref("general.skins.selectedSkin", "phoenitymodern");
user_pref("intl.charsetmenu.browser.cache", "windows-1251, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("plugin.soname.list", "libXext.so");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signed.applets.codebase_principal_support", true);
user_pref("spellchecker.dictionary", "en-US");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/getkey?client=navclient-auto-ffox2.0&", 1165886465);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1254044006);
user_pref("urlclassifier.tableversion.goog-black-enchash", "1.14444");
user_pref("urlclassifier.tableversion.goog-black-url", "1.7417");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.18");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
